### PR TITLE
feat: German language and more

### PR DESCRIPTION
**Pull request by mprangenberg**
I've added a bunch of german dictionaries and language support to a bunch of commands.

My main focus is/was on forbidden lands, as i am currently in a campaign. As soon as i get the pdfs from the bitter reach crowdfunding i will add those translations, too.

I'll try to add more in the other systems when i get time and my hands on them. I currently own the following german books (all = published to date): myz core book, all coriolis, all fbl, all tales from the loop/things from the flood and i can also get my hands on the alien core book.
Vaesen and twilight crowdfundings were announced to probably start within this year.

Feel free to contact me for any help/tasks.

Kind Regards,
Michael

### CODE REVIEW

**Comment by Stefouch** [comment]
Wow! That's a huge update! Thank you for your help!
Give me a few days to review it!

**Comment by Stefouch** [comment]
Hi @mprangenberg !

I was very busy with the **t2k4e** repo (a conversion of Twilight 2000 for The Foundry VTT) and another private one for Fria Ligan. I will return to the bot by next week!

I apologize for the delay. I see your involvement in the project. I am thankful for your help!
It's just that I need to triple check the changes as any commit to the `master` branch will trigger an update at the bot's hosting server.
I use the `develop` branch for upcoming changes before they are merged to `master` for a new version release of the bot.

**Comment by mprangenberg** [comment]
Yeah, i'm sorry, that was my mistake. I can close this pull request and make one for the develop branch if you'd like.

**Comment by Stefouch** [comment]
If it's OK for you, yes please!

Le dim. 14 févr. 2021 à 20:14, mprangenberg <notifications@github.com> a
écrit :

**Comment by mprangenberg** [comment]
Closing this pull request, as promised, to open one in another branch

**Pull request closed without merging**
